In [1]:
import numpy as np

In [2]:
rd5 = np.random.random([5, 5])

In [3]:
print(rd5)

[[0.67588002 0.39857002 0.20611159 0.01612681 0.74945239]
 [0.50001781 0.4363525  0.51376764 0.10800809 0.80375314]
 [0.82204042 0.63070188 0.0547008  0.14264139 0.5935965 ]
 [0.75007755 0.87407694 0.384653   0.25115618 0.14994737]
 [0.8895249  0.50504913 0.26323893 0.05033357 0.93734591]]


In [7]:
print(np.random.random([5, 5]))

[[0.13941494 0.31692446 0.89404522 0.8579769  0.47457665]
 [0.91898705 0.00201377 0.8830034  0.70111395 0.78914401]
 [0.31635412 0.44913117 0.28329968 0.79513089 0.4169563 ]
 [0.68443773 0.64670121 0.18687077 0.72321369 0.16368902]
 [0.31847417 0.13696727 0.74667016 0.11387914 0.08376455]]


In [21]:
np.random.seed(123)

In [37]:
print(np.random.random([2, 2]))

[[0.66931378 0.58593655]
 [0.6249035  0.67468905]]
